name: Deployment

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    - uses: actions/upload-artifact@v3
      with:
        name: jar
        path: build/libs

  send-jar:
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: Download jar
        uses: actions/download-artifact@v3
        with:
          name: jar
      - name: Send jar to remote server
        uses: appleboy/scp-action@master
        with:
          host: 34.22.105.223
          username: choroc2020
          source: "devlog_springboot-0.0.1-SNAPSHOT.jar"
          target: "/home/choroc2020"
          key: ${{ secrets.PRIVATE_KEY }}

  run-app:
    needs: send-jar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Move deploy.sh
        uses: appleboy/scp-action@master
        with:
          host: 34.22.105.223
          username: choroc2020
          source: "deploy.sh"
          target: "/home/choroc2020"
          key: ${{ secrets.PRIVATE_KEY }}
      - name: Execute script
        uses: appleboy/ssh-action@master
        with:
          username: choroc2020
          host: 34.22.105.223
          key: ${{ secrets.PRIVATE_KEY }}
          script_stop: true
          script: cd /home/choroc2020 && chmod +x deploy.sh && ./deploy.sh
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
