# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Deployment

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    - uses: actions/upload-artifact@v3
      with:
        name: jar
        path: build/libs
        
  send-jar:
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: Download jar
        uses: actions/download-artifact@v3
        with:
          name: jar
      - name: Send jar to remote server
        uses: appleboy/scp-action@master
        with:
          host: 34.22.85.38
          username: hyojae5945
          source: "devlog_springboot-0.0.1-SNAPSHOT.jar"
          target: "/home/hyojae5945"
          key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQClv/xQ5v4/iQkNj35UL7oxG0py2UOB4G1+jYyDxMlTGgJwvfeh/dZvIiBYwaagKSNPWVM5cgyBbbcy3UBFF7Lb1nlR/nLzJykZiOMrHI2of91o5UoqWIOs8qiW5G04MzZaMafdAwDxpFbs2oGKHkrk381v2Q0EPUvFCVfYGfgdaE+p41Gz8u/YB+oYG3n/PWSN1ZGfVuCMRgEwOVL4Za/QoAAEx/iGgRl/CnUJSEx3uUg6+nNVdWFzS2bGDOlsBlGyKVv2ibTKDa+pnsihA+Oon/eivFMUaWBd63orp6+VdFPU4HwVybYalq4sJnrIE0IrQyecmhiak9jnPsVHFGQX6NfFURGWwoowcyddRYHH/d3CUzEQ9RJomPb6lJa27SLJmSR9pF8KyTL0q4O0qKZ8uRPti1I61fTZ2cDL00Lui2JmK9h+ZtxNedFFD5DtLMEy2mlcK63XVeNelVR0xG0ZBOUd1udGkYAiOGFNg7+uIn1d8o00U57faNOFAj1KO5k= hyojae5945@gmail.com
  
  run-app:
    needs: send-jar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Move deploy.sh
        uses: appleboy/scp-action@master
        with:
          host: 34.22.85.38
          username: hyojae5945
          source: "deploy.sh"
          target: "/home/hyojae5945"
          key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQClv/xQ5v4/iQkNj35UL7oxG0py2UOB4G1+jYyDxMlTGgJwvfeh/dZvIiBYwaagKSNPWVM5cgyBbbcy3UBFF7Lb1nlR/nLzJykZiOMrHI2of91o5UoqWIOs8qiW5G04MzZaMafdAwDxpFbs2oGKHkrk381v2Q0EPUvFCVfYGfgdaE+p41Gz8u/YB+oYG3n/PWSN1ZGfVuCMRgEwOVL4Za/QoAAEx/iGgRl/CnUJSEx3uUg6+nNVdWFzS2bGDOlsBlGyKVv2ibTKDa+pnsihA+Oon/eivFMUaWBd63orp6+VdFPU4HwVybYalq4sJnrIE0IrQyecmhiak9jnPsVHFGQX6NfFURGWwoowcyddRYHH/d3CUzEQ9RJomPb6lJa27SLJmSR9pF8KyTL0q4O0qKZ8uRPti1I61fTZ2cDL00Lui2JmK9h+ZtxNedFFD5DtLMEy2mlcK63XVeNelVR0xG0ZBOUd1udGkYAiOGFNg7+uIn1d8o00U57faNOFAj1KO5k= hyojae5945@gmail.com
      - name: Execute script
        uses: appleboy/ssh-action@master
        with:
          username: hyojae5945
          host: 34.22.85.38
          key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQClv/xQ5v4/iQkNj35UL7oxG0py2UOB4G1+jYyDxMlTGgJwvfeh/dZvIiBYwaagKSNPWVM5cgyBbbcy3UBFF7Lb1nlR/nLzJykZiOMrHI2of91o5UoqWIOs8qiW5G04MzZaMafdAwDxpFbs2oGKHkrk381v2Q0EPUvFCVfYGfgdaE+p41Gz8u/YB+oYG3n/PWSN1ZGfVuCMRgEwOVL4Za/QoAAEx/iGgRl/CnUJSEx3uUg6+nNVdWFzS2bGDOlsBlGyKVv2ibTKDa+pnsihA+Oon/eivFMUaWBd63orp6+VdFPU4HwVybYalq4sJnrIE0IrQyecmhiak9jnPsVHFGQX6NfFURGWwoowcyddRYHH/d3CUzEQ9RJomPb6lJa27SLJmSR9pF8KyTL0q4O0qKZ8uRPti1I61fTZ2cDL00Lui2JmK9h+ZtxNedFFD5DtLMEy2mlcK63XVeNelVR0xG0ZBOUd1udGkYAiOGFNg7+uIn1d8o00U57faNOFAj1KO5k= hyojae5945@gmail.com
          script_stop: true
          script: cd /home/hyojae5945 && chmod +x deploy.sh && ./deploy.sh
